baseurl = "http://didipkerabat.com/"
title = "Fun with Go & Python"

[params]
    author = "Didip Kerabat"
    avatarUrl = "https://pbs.twimg.com/profile_images/1196816707/black-turtleneck.jpg"
    githubUrl = "http://github.com/didip"
    twitterUrl = "http://www.twitter.com/didip"
    linkedinUrl = "http://www.linkedin.com/in/didipkerabat"

[indexes]
    tag = "tags"
    topic = "topics"

